### ISSUE TITLE
Add data persistency

### ISSUE THREAD

**Issue by aliir74** [aliir74/azta-telegram-bot#2]
# Problem
Now, when we deploy or docker container restarts, all the states will be lost. We need to add a database (probably Redis for convenient) to the project to prevent data loss.

# Todo
- [x] Add redis to project
- [x] Change the project structure to use docker-compose with Redis
- [x] Connect grammy package to Redis
